<?php

namespace Acme\DemoBundle\Entity\Demo;

use Doctrine\ORM\EntityRepository;

/**
 * Annee_Formation_EtudiantRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Annee_Formation_EtudiantRepository extends EntityRepository
{
}
