<?php

namespace Acme\DemoBundle\Entity\Demo;

use Doctrine\ORM\EntityRepository;

/**
 * remarque_responsable_rapportRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class remarque_responsable_rapportRepository extends EntityRepository
{
}
