<?php

namespace Qcm\TestBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * DateFormationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DateFormationRepository extends EntityRepository
{
}
